#### **Library Imports**

In [1]:
### Data Ingestion
import tempfile
from pathlib import Path
import py7zr

# Data Manipulation
import numpy as np
import pandas as pd

# Data Visualization
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
ROOT = Path.cwd().parent
path = ROOT / "data" / "nov_data" / "_parquet_cache" / "5FT0217"

In [3]:
# Grab two parquet files for exploration
files = sorted(path.glob("2025-11-0*.parquet"))[:2]

In [4]:
# Validate paths
files

[PosixPath('/Users/parisheard/Documents/umich/courses/mastery_project/data/nov_data/_parquet_cache/5FT0217/2025-11-01.parquet'),
 PosixPath('/Users/parisheard/Documents/umich/courses/mastery_project/data/nov_data/_parquet_cache/5FT0217/2025-11-01_5FT0217.parquet')]

In [5]:
# Extract date from filename and concatenate DataFrames
dfs = []
for f in files:
    df = pd.read_parquet(f)
    df['Date'] = f.stem.split("_")[0]  # Extract date from filename
    dfs.append(df)

df = pd.concat(dfs, ignore_index=True)
df['Date'] = pd.to_datetime(df['Date'])

In [6]:
df.head()

,Timestamp,EEC1_Engine.ActualEngPercentTorque,EEC1_Engine.DriversDemandEngPercentTorque,EEC1_Engine.EngSpeed,EEC1_Engine.SrcAddrssOfCntrllngDvcForEngCtrl,LFE_Engine.EngFuelRate,EC1_Engine.EngReferenceTorque,EEC2_Engine.AccelPedalPos1,EEC2_Engine.ActlMaxAvailableEngPercentTorque,CCVS1_Engine.BrakeSwitch,...,TTC0016_FOC,TTC0017_FMI,TTC0017_FOC,NavSatNum,JammingSt,cwSuppress,HDOP,GpsReset,AutoMountState,Date
0,32228.863,0.0,0.0,1387.75,11.0,0.0,2386.0,0.0,44.0,0.0,...,0.0,7.0,3.0,28.0,0.0,21.0,0.75,0.0,0.0,2025-11-01
1,32228.963,0.0,0.0,1388.00,11.0,0.0,2386.0,0.0,44.0,0.0,...,0.0,7.0,3.0,28.0,0.0,21.0,0.75,0.0,0.0,2025-11-01
2,32229.064,0.0,0.0,1388.25,11.0,0.0,2386.0,0.0,44.0,0.0,...,0.0,7.0,3.0,28.0,0.0,21.0,0.75,0.0,0.0,2025-11-01
3,32229.164,0.0,0.0,1385.75,11.0,0.0,2386.0,0.0,44.0,0.0,...,0.0,7.0,3.0,28.0,0.0,21.0,0.75,0.0,0.0,2025-11-01
4,32229.264,0.0,0.0,1385.50,11.0,0.0,2386.0,0.0,44.0,0.0,...,0.0,7.0,3.0,28.0,0.0,21.0,0.75,0.0,0.0,2025-11-01

In [7]:
# Sort by Date and Timestamp
df = df.sort_values(['Date', 'Timestamp']).reset_index(drop=True)

In [8]:
# Drop all rows with NaN values
df = df.dropna()

In [9]:
df.head()

,Timestamp,EEC1_Engine.ActualEngPercentTorque,EEC1_Engine.DriversDemandEngPercentTorque,EEC1_Engine.EngSpeed,EEC1_Engine.SrcAddrssOfCntrllngDvcForEngCtrl,LFE_Engine.EngFuelRate,EC1_Engine.EngReferenceTorque,EEC2_Engine.AccelPedalPos1,EEC2_Engine.ActlMaxAvailableEngPercentTorque,CCVS1_Engine.BrakeSwitch,...,TTC0016_FOC,TTC0017_FMI,TTC0017_FOC,NavSatNum,JammingSt,cwSuppress,HDOP,GpsReset,AutoMountState,Date
0,2.804,54.0,0.0,0.00,0.0,0.0,0.0,0.0,54.0,0.0,...,0.0,255.0,0.0,24.0,0.0,15.0,0.64,0.0,0.0,2025-11-01
1,2.904,54.0,0.0,0.00,0.0,0.0,0.0,0.0,54.0,0.0,...,0.0,255.0,0.0,24.0,0.0,15.0,0.64,0.0,0.0,2025-11-01
2,3.004,54.0,0.0,0.00,0.0,0.0,0.0,0.0,54.0,0.0,...,0.0,255.0,0.0,24.0,0.0,15.0,0.64,0.0,0.0,2025-11-01
3,3.104,54.0,0.0,0.00,0.0,0.0,0.0,0.0,54.0,0.0,...,0.0,255.0,0.0,24.0,0.0,15.0,0.64,0.0,0.0,2025-11-01
4,3.200,7.0,0.0,651.25,0.0,2.7,2386.0,0.0,48.8,0.0,...,0.0,255.0,0.0,22.0,0.0,0.0,0.76,0.0,0.0,2025-11-01

In [10]:
df.tail()

,Timestamp,EEC1_Engine.ActualEngPercentTorque,EEC1_Engine.DriversDemandEngPercentTorque,EEC1_Engine.EngSpeed,EEC1_Engine.SrcAddrssOfCntrllngDvcForEngCtrl,LFE_Engine.EngFuelRate,EC1_Engine.EngReferenceTorque,EEC2_Engine.AccelPedalPos1,EEC2_Engine.ActlMaxAvailableEngPercentTorque,CCVS1_Engine.BrakeSwitch,...,TTC0016_FOC,TTC0017_FMI,TTC0017_FOC,NavSatNum,JammingSt,cwSuppress,HDOP,GpsReset,AutoMountState,Date
580951,46349.070,0.0,0.0,0.0,0.0,0.0,2386.0,0.0,0.0,0.0,...,0.0,7.0,3.0,22.0,0.0,20.0,0.79,0.0,0.0,2025-11-01
580952,46349.172,0.0,0.0,0.0,0.0,0.0,2386.0,0.0,0.0,0.0,...,0.0,7.0,3.0,22.0,0.0,20.0,0.79,0.0,0.0,2025-11-01
580953,46349.270,0.0,0.0,0.0,0.0,0.0,2386.0,0.0,0.0,0.0,...,0.0,7.0,3.0,22.0,0.0,20.0,0.79,0.0,0.0,2025-11-01
580954,46349.371,0.0,0.0,0.0,0.0,0.0,2386.0,0.0,0.0,0.0,...,0.0,7.0,3.0,22.0,0.0,20.0,0.79,0.0,0.0,2025-11-01
580955,46349.473,0.0,0.0,0.0,0.0,0.0,2386.0,0.0,0.0,0.0,...,0.0,7.0,3.0,22.0,0.0,20.0,0.79,0.0,0.0,2025-11-01

In [11]:
print(f'Dates: {df["Date"].unique()}')

Dates: <DatetimeArray>
['2025-11-01 00:00:00']
Length: 1, dtype: datetime64[ns]

In [12]:
ts = df['Timestamp']
diffs = ts.diff()

print('Basic Stats (in seconds):')
print(diffs.describe())

print('\nQuantiles:')
print(diffs.quantile([0.5, 0.9, 0.99, 0.999]))

print('\nNegative Diffs (Resets):', ( diffs < 0 ).sum())
print('Zero Diffs (Duplicates):', ( diffs == 0 ).sum())
print('Positive Diffs (Normal):', ( diffs > 0 ).sum())
print('Diff Gap (>60s):', ( diffs > 60 ).sum())

Basic Stats (in seconds):
count    580950.000000
mean          0.079777
std          18.305811
min           0.000000
25%           0.015000
50%           0.054000
75%           0.099000
max       13952.726000
Name: Timestamp, dtype: float64

Quantiles:
0.500    0.054
0.900    0.101
0.990    0.102
0.999    0.102
Name: Timestamp, dtype: float64

Negative Diffs (Resets): 0
Zero Diffs (Duplicates): 7977
Positive Diffs (Normal): 572973
Diff Gap (>60s): 1

Locating the Negative Differential

In [13]:
neg_idx = df['Timestamp'].diff().lt(0)
df.loc[neg_idx, ['Date', 'Timestamp']].head()

Empty DataFrame
Columns: [Date, Timestamp]
Index: []

In [14]:
prev_idx = df['Timestamp'].diff().idxmin()
df.loc[prev_idx-5:prev_idx+5, ['Date', 'Timestamp']]

         Date  Timestamp
48 2025-11-01      4.111
49 2025-11-01      4.115
50 2025-11-01      4.200
51 2025-11-01      4.205
52 2025-11-01      4.209
53 2025-11-01      4.209
54 2025-11-01      4.210
55 2025-11-01      4.212
56 2025-11-01      4.214
57 2025-11-01      4.215
58 2025-11-01      4.300

Locating the Positive Differential

In [15]:
pos_idx = df['Timestamp'].diff().gt(1000)
df.loc[pos_idx, ['Date', 'Timestamp']].head()

             Date  Timestamp
440108 2025-11-01  32228.863

In [16]:
prev_idx = df['Timestamp'].diff().idxmax()
df.loc[prev_idx-5:prev_idx+5, ['Date', 'Timestamp']]

             Date  Timestamp
440103 2025-11-01  18275.736
440104 2025-11-01  18275.836
440105 2025-11-01  18275.936
440106 2025-11-01  18276.037
440107 2025-11-01  18276.137
440108 2025-11-01  32228.863
440109 2025-11-01  32228.963
440110 2025-11-01  32229.064
440111 2025-11-01  32229.164
440112 2025-11-01  32229.264
440113 2025-11-01  32229.363

Analysis of timestamp first differences confirms that the data is sampled at approximately 10Hz (99th percentile: 0.102s), indicating a stable high-frequency logging under normal operation.

Two distinct dicontinuity behaviors were isolated and identified, along with insights from the client:

1. **Negative Timestamp Differences (Decrease)**
These events occur at day boundaries (presumably midnight, relative to timezone considerations), and represent system resets where the timestamp restarts from a low value. This aligns with day transitions or system reinitialization across files.

2. **Large Positive Timestamp Differences (Increase)**
These events occur, presumably, within the same calendar day and were confirmed by the client to represent system reboots as a driver restarts their vehicle. These events do not reset the timestamp to zero, but instead resume a new, larger baseline value.

To robustly segment data into continuous operational sessions ("time periods"), both conditions must be treated as hard boundaries with established limits. Given the 10Hz sampling rate in this consideration, any timestamp difference significantly larger than expected sampling jitter safely indicates a reboot or discontinuity.

All downstream event detection and context window extraction should be constrained within these inferred time periods to prevent stitching together unrelated driving sessions, and ensure simultaneously sessions remain connnected.

In [17]:
# pull idx around each timestamp reset and gap
reset_idx = df['Timestamp'].diff().lt(0)
gap_idx = df['Timestamp'].diff().gt(60)

reset_samples = df.loc[reset_idx]
gap_samples = df.loc[gap_idx]

In [18]:
reset_samples

Empty DataFrame
Columns: [Timestamp, EEC1_Engine.ActualEngPercentTorque, EEC1_Engine.DriversDemandEngPercentTorque, EEC1_Engine.EngSpeed, EEC1_Engine.SrcAddrssOfCntrllngDvcForEngCtrl, LFE_Engine.EngFuelRate, EC1_Engine.EngReferenceTorque, EEC2_Engine.AccelPedalPos1, EEC2_Engine.ActlMaxAvailableEngPercentTorque, CCVS1_Engine.BrakeSwitch, CCVS1_Engine.CruiseCtrlActive, CCVS1_Engine.CruiseCtrlSetSpeed, CCVS1_Engine.CruiseCtrlStates, CCVS1_Engine.WheelBasedVehicleSpeed, DPFC1_Engine.DieselParticulateFilterLampCmd, DPFC1_Engine.DieselParticulateFilterStatus, DPFC1_Engine.DslPrtcltFltrActvRgnrationStatus, DPFC1_Engine.DslPrtcltFltrPssvRgnrationStatus, DPFC1_Engine.ExhaustSystemHighTempLampCmd, AT1S1_Engine.Aftrtrtmnt1DslPrtcltFltrStLdRgnr, AT1S1_Engine.DslPrtcltFltr1TmSncLstActvRgnrtn, AT1S1_Engine.DslPrtclteFilter1SootLoadPercent, ERC1_Retarder.ActualRetarderPercentTorque, ERC1_Retarder.SrcAddrssOfCntrllngDvcFrRtrdrCtr, RC_Retarder.ReferenceRetarderTorque, TC1_ShiftCon_to_Trans.TransRequestedGear, ETC2_Transmission.TransActualGearRatio, ETC2_Transmission.TransCurrentGear, ETC2_Transmission.TransSelectedGear, ETC1_Transmission.TransDrivelineEngaged, ETC1_Transmission.TransShiftInProcess, TSC1_Trans_to_Engine.EngRequestedTorque_TorqueLimit, TSC1_Trans_to_Retarder.EngRequestedTorque_TorqueLimit, TSC1_Brakes_to_Retarder.EngRequestedTorque_TorqueLimit, CCVS1_Cab_Controller.BrakeSwitch, CCVS1_Cab_Controller.CruiseCtrlEnableSwitch, CCVS1_Cab_Controller.CruiseCtrlResumeSwitch, CCVS1_Cab_Controller.CruiseCtrlSetSwitch, HRW_Brakes.FrontAxleLeftWheelSpeed, HRW_Brakes.FrontAxleRightWheelSpeed, HRW_Brakes.RearAxleLeftWheelSpeed, HRW_Brakes.RearAxleRightWheelSpeed, OEL_BodyController.TurnSignalSwitch, LD.LeftTurnSignalLights, LD.RightTurnSignalLights, LCMD.LeftTurnSignalLightsCmd, LCMD.RightTurnSignalLightsCmd, EBC2_Brakes.FrontAxleSpeed, EBC2_Brakes.RelativeSpeedFrontAxleLeftWheel, EBC2_Brakes.RelativeSpeedFrontAxleRightWheel, EBC2_Brakes.RelativeSpeedRearAxle1LeftWheel, EBC2_Brakes.RelativeSpeedRearAxle1RightWheel, EBC2_Brakes.RelativeSpeedRearAxle2LeftWheel, EBC2_Brakes.RelativeSpeedRearAxle2RightWheel, ACC1_Radar.AdaptiveCruiseCtrlMode, ACC1_Radar.AdaptiveCruiseCtrlSetSpeed, ACC1_Radar.DistanceToForwardVehicle, ACC1_Radar.SpeedOfForwardVehicle, ACC1_Radar.TargetDetected, iQCU_Status_1.DistanceToForwardVehicle, iQCU_Status_1.RadarFaultMode_NA, iQCU_Status_1.Speed2D_FWVehicle, iQCU_Status_1.Truck_Height, VDS_FC.Altitude, VDS_FC.CompassBearing, VDS_FC.NavigationBasedVehicleSpeed, VP_RP_80.Latitude, VP_RP_80.Longitude, VP2_FC.Horizontal_Precision, VP2_FC.Number_Satellites_View, ACCS_RP.LateralAccelerationExRange, ACCS_RP.LongitudinalAccelerationExRange, ACCS_RP.VerticalAccelerationExRange, ARI_RP.PitchRateExRange, ARI_RP.RollRateExRange, ARI_RP.YawRateExRange, EH_not_localized.EH_not_localized, CVW.GrossCombinationVehicleWeight, EBC1_Brakes.BrakePedalPos, EBC1_Brakes.EBSBrakeSwitch, Reserved1, Reserved2, iQC1.iQCMode, iQEH1.iQEHState, iQPC3.iQConvergencePercentage, iQVLPE1.iQGrossVehicleWeightEst, MS_Weather_Telematics_Static.Precipitation_Intensity, MS_Weather_Telematics_Static.Precipitation_Probability, MS_Weather_Telematics_Static.Temperature, MS_Weather_Telematics_Dynanmic.Visibility, MS_Weather_Telematics_Dynanmic.Wind_Bearing, MS_Weather_Telematics_Dynanmic.Wind_Speed, PCC1.PCCState, VDHR_Engine.HghRsolutionTotalVehicleDistance, VDS_RP_80.Altitude, iQCU_UC_Status2.IQCU_BatteryVoltage, iQCU_UC_Status2.IQCU_IgnitionVoltage, ETC7_Transmission.TransWarningIndicator, LFC_Engine.EngTotalFuelUsed, LFC_Engine.EngTripFuel, ...]
Index: []

[0 rows x 294 columns]

In [19]:
gap_samples

,Timestamp,EEC1_Engine.ActualEngPercentTorque,EEC1_Engine.DriversDemandEngPercentTorque,EEC1_Engine.EngSpeed,EEC1_Engine.SrcAddrssOfCntrllngDvcForEngCtrl,LFE_Engine.EngFuelRate,EC1_Engine.EngReferenceTorque,EEC2_Engine.AccelPedalPos1,EEC2_Engine.ActlMaxAvailableEngPercentTorque,CCVS1_Engine.BrakeSwitch,...,TTC0016_FOC,TTC0017_FMI,TTC0017_FOC,NavSatNum,JammingSt,cwSuppress,HDOP,GpsReset,AutoMountState,Date
440108,32228.863,0.0,0.0,1387.75,11.0,0.0,2386.0,0.0,44.0,0.0,...,0.0,7.0,3.0,28.0,0.0,21.0,0.75,0.0,0.0,2025-11-01

In [20]:
# print all columns
print(df.columns.tolist())

# 'VP_RP_80.Latitude'
# 'VP_RP_80.Longitude'

['Timestamp', 'EEC1_Engine.ActualEngPercentTorque', 'EEC1_Engine.DriversDemandEngPercentTorque', 'EEC1_Engine.EngSpeed', 'EEC1_Engine.SrcAddrssOfCntrllngDvcForEngCtrl', 'LFE_Engine.EngFuelRate', 'EC1_Engine.EngReferenceTorque', 'EEC2_Engine.AccelPedalPos1', 'EEC2_Engine.ActlMaxAvailableEngPercentTorque', 'CCVS1_Engine.BrakeSwitch', 'CCVS1_Engine.CruiseCtrlActive', 'CCVS1_Engine.CruiseCtrlSetSpeed', 'CCVS1_Engine.CruiseCtrlStates', 'CCVS1_Engine.WheelBasedVehicleSpeed', 'DPFC1_Engine.DieselParticulateFilterLampCmd', 'DPFC1_Engine.DieselParticulateFilterStatus', 'DPFC1_Engine.DslPrtcltFltrActvRgnrationStatus', 'DPFC1_Engine.DslPrtcltFltrPssvRgnrationStatus', 'DPFC1_Engine.ExhaustSystemHighTempLampCmd', 'AT1S1_Engine.Aftrtrtmnt1DslPrtcltFltrStLdRgnr', 'AT1S1_Engine.DslPrtcltFltr1TmSncLstActvRgnrtn', 'AT1S1_Engine.DslPrtclteFilter1SootLoadPercent', 'ERC1_Retarder.ActualRetarderPercentTorque', 'ERC1_Retarder.SrcAddrssOfCntrllngDvcFrRtrdrCtr', 'RC_Retarder.ReferenceRetarderTorque', 'TC1_ShiftCon_to_Trans.TransRequestedGear', 'ETC2_Transmission.TransActualGearRatio', 'ETC2_Transmission.TransCurrentGear', 'ETC2_Transmission.TransSelectedGear', 'ETC1_Transmission.TransDrivelineEngaged', 'ETC1_Transmission.TransShiftInProcess', 'TSC1_Trans_to_Engine.EngRequestedTorque_TorqueLimit', 'TSC1_Trans_to_Retarder.EngRequestedTorque_TorqueLimit', 'TSC1_Brakes_to_Retarder.EngRequestedTorque_TorqueLimit', 'CCVS1_Cab_Controller.BrakeSwitch', 'CCVS1_Cab_Controller.CruiseCtrlEnableSwitch', 'CCVS1_Cab_Controller.CruiseCtrlResumeSwitch', 'CCVS1_Cab_Controller.CruiseCtrlSetSwitch', 'HRW_Brakes.FrontAxleLeftWheelSpeed', 'HRW_Brakes.FrontAxleRightWheelSpeed', 'HRW_Brakes.RearAxleLeftWheelSpeed', 'HRW_Brakes.RearAxleRightWheelSpeed', 'OEL_BodyController.TurnSignalSwitch', 'LD.LeftTurnSignalLights', 'LD.RightTurnSignalLights', 'LCMD.LeftTurnSignalLightsCmd', 'LCMD.RightTurnSignalLightsCmd', 'EBC2_Brakes.FrontAxleSpeed', 'EBC2_Brakes.RelativeSpeedFrontAxleLeftWheel', 'EBC2_Brakes.RelativeSpeedFrontAxleRightWheel', 'EBC2_Brakes.RelativeSpeedRearAxle1LeftWheel', 'EBC2_Brakes.RelativeSpeedRearAxle1RightWheel', 'EBC2_Brakes.RelativeSpeedRearAxle2LeftWheel', 'EBC2_Brakes.RelativeSpeedRearAxle2RightWheel', 'ACC1_Radar.AdaptiveCruiseCtrlMode', 'ACC1_Radar.AdaptiveCruiseCtrlSetSpeed', 'ACC1_Radar.DistanceToForwardVehicle', 'ACC1_Radar.SpeedOfForwardVehicle', 'ACC1_Radar.TargetDetected', 'iQCU_Status_1.DistanceToForwardVehicle', 'iQCU_Status_1.RadarFaultMode_NA', 'iQCU_Status_1.Speed2D_FWVehicle', 'iQCU_Status_1.Truck_Height', 'VDS_FC.Altitude', 'VDS_FC.CompassBearing', 'VDS_FC.NavigationBasedVehicleSpeed', 'VP_RP_80.Latitude', 'VP_RP_80.Longitude', 'VP2_FC.Horizontal_Precision', 'VP2_FC.Number_Satellites_View', 'ACCS_RP.LateralAccelerationExRange', 'ACCS_RP.LongitudinalAccelerationExRange', 'ACCS_RP.VerticalAccelerationExRange', 'ARI_RP.PitchRateExRange', 'ARI_RP.RollRateExRange', 'ARI_RP.YawRateExRange', 'EH_not_localized.EH_not_localized', 'CVW.GrossCombinationVehicleWeight', 'EBC1_Brakes.BrakePedalPos', 'EBC1_Brakes.EBSBrakeSwitch', 'Reserved1', 'Reserved2', 'iQC1.iQCMode', 'iQEH1.iQEHState', 'iQPC3.iQConvergencePercentage', 'iQVLPE1.iQGrossVehicleWeightEst', 'MS_Weather_Telematics_Static.Precipitation_Intensity', 'MS_Weather_Telematics_Static.Precipitation_Probability', 'MS_Weather_Telematics_Static.Temperature', 'MS_Weather_Telematics_Dynanmic.Visibility', 'MS_Weather_Telematics_Dynanmic.Wind_Bearing', 'MS_Weather_Telematics_Dynanmic.Wind_Speed', 'PCC1.PCCState', 'VDHR_Engine.HghRsolutionTotalVehicleDistance', 'VDS_RP_80.Altitude', 'iQCU_UC_Status2.IQCU_BatteryVoltage', 'iQCU_UC_Status2.IQCU_IgnitionVoltage', 'ETC7_Transmission.TransWarningIndicator', 'LFC_Engine.EngTotalFuelUsed', 'LFC_Engine.EngTripFuel', 'HOURS_Engine.EngTotalHoursOfOperation', 'VDHR_Engine.HighResolutionTripDistance', 'HRLFC_Engine.HighResolutionEngTotalFuelUsed', 'iQEH6.iQCMaxSpdVarPredHor', 'iQEH6.iQCRefSpdVarPredHor', 'iQEH6.iQCMinSpdVarPredHor', 'iQEH3.iQTargSpeed', 'TSC1_Brakes_to_Engine.EngRequestedTorque_TorqueLimit', 'vBase.ignPresent', 'IcdMainCounter', 'ACC1_Radar.ForwardCollisionWarning', 'IQC1.IQCDriverAlert', 'IQCU_FCR.PSGRRadarDistVeh_Detected', 'IQCU_FCR.PSGRSideRadar_DistRightSideVeh', 'IQCU_FCR.RadarMisalignHdwrYawAng', 'IQCU_FCR.RadarMisalignAutoCalibYawAng', 'IQCU_FCR.LateralDistanceToForwardVehicle', 'TabletMqttHealth', 'ECU.Temp0', 'ECU.Temp1', 'ECU.Temp2', 'ECU.Temp3', 'ECU.Temp4', 'ECU.Temp5', 'Tablet.UserButtonPress', 'Engine.DM1.AmberLamp', 'Engine.DM1.SPN', 'Trans.DM1.AmberLamp', 'Trans.DM1.SPN', 'Brakes.DM1.AmberLamp', 'Brakes.DM1.SPN', 'Radar.DM1.AmberLamp', 'Radar.DM1.SPN', 'AEB.DM1.AmberLamp', 'AEB.DM1.SPN', 'ShiftConsole.DM1.AmberLamp', 'ShiftConsole.DM1.SPN', 'Cluster.DM1.AmberLamp', 'Cluster.DM1.SPN', 'MgmtComp.DM1.AmberLamp', 'MgmtComp.DM1.SPN', 'EEC3.NominalFrictionPercentTorque', 'IQC1.iQCControlMode', 'Tablet.InFocus', 'IQC1.iQCHealth', 'IQC1.iQCPreviewMode', 'ACC1.RoadCurvature', 'IQVS1.iQRoadGrade', 'IQPC1.iQMinimumSpeed', 'IQPC1.iQReferenceSpeed', 'IQPC1.iQMaximumSpeed', 'IQCP3.iQPercentDesiredEngTrq', 'IQPC3.iQPercentDesiredEngRetarderTrq', 'IQVLPE1.iQAerodynamicDragEst', 'IQVLPE1.iQGrossVehicleWeightEst', 'IQVLPE1.iQmu0Est', 'IQVLPE1.iQmu1Est', 'IQVLPE1.iQmu2Est', 'IQVS1.iQFilteredVehicleVelocity', 'IQVS1.iQFilteredLongAccel', 'IQVS1.iQWheelTorque', 'EH_Position_20_SrE0.ADAS_Posn_Offset', 'IQEH1.iQLCAGradeCur', 'IQEH1.iQLCAElevCur', 'IQEH3.iQLCAIsRampCur', 'IQEH1.iQLCAFuncClassCur', 'IQEH1.iQLCAHeadingCur', 'IQEH1.iQLCARoadCur', 'IQEH3.iQLCASpeedLimCur', 'IQEH2.iQLCALatCur', 'IQEH2.iQLCALongCur', 'IQEH4.RMVCurrentPosition', 'CCVS1_ManagementComputer.CruiseCtrlBrakeSwitch', 'CCVS1_ManagementComputer.CruiseCtrlEnableSwitch', 'CCVS1_ManagementComputer.CruiseCtrlResumeSwitch', 'CCVS1_ManagementComputer.CruiseCtrlSetSwitch', 'CCVS1_ManagementComputer.CruiseCtrlActive', 'CCVS1_ManagementComputer.CruiseCtrlStates', 'CCVS1_Cab_Controller.CruiseCtrlStates', 'IQC1.iQCActuatorControlMode', 'PCC1.PCCEventinRange', 'PCC1.PCCSetSpeedOffset', 'PCC1.PCCSpdDrivelineDise', 'PCC1.PCCSpeedEventIndica', 'PCC1.RoadwayNextGradeDis', 'PCC1.RoadwayNextGrade', 'PCC1.RoadwayPresentGRade', 'PCC1.VSpeedCtrlOverrideI', 'PCC1.VehicleSpeedCtrlOve', 'LFE_Engine.EngAverageFuelEconomy', 'EH_Re_routing_29_SrE0.EH_re_routing', 'IQC_SpeedGov.OvrdAsstState', 'IQC_SpeedGov.OvrdAssistFeatAvailTime', 'IQC_SpeedGov.OvrdAssistMaxAvailTime', 'IQC_SpeedGov.TimeToOvrdAsstLockout', 'IQC_SpeedGov.TimeToNextOvrdAssist', 'IQC_SpeedGov.FuncMode', 'IQC_SpeedGov.FuncState', 'IQC_SpeedGov.GovSpd_kph', 'EH_App_Logger_Comm.EH_Event_ID_ext', 'ERC1_Retarder.ActlMxAvlblRetarderPercentTorque', 'iQPC3.iQDesiredGear', 'iQVS1.iQRoadGrade_GPS', 'iQVS1.iQRoadGrade_IMU', 'HRLFC_Engine.HighResolutionEngTripFuel', 'IQEH5.Latitude', 'IQEH5.Longitude', 'IQEH6.Fused_pose_vehicle_speed', 'IQCU_IMU_Status_4.PathCurvature', 'IQCU_IMU_Status_4.RoadBank', 'IQCU_IMU_Status_4.SideSlip', 'IQCU_IMU_Status_4.SideSlipRate', 'IQCU_IMU_Status_4.RollAngle', 'IQCU_IMU_Status_4.PitchAngle', 'IQCU_IMU_Status_4.YawAngle', 'IQCU_IMU_Status_5.AccelBias_x', 'IQCU_IMU_Status_5.AccelBias_y', 'IQCU_IMU_Status_5.AccelBias_z', 'IQCU_IMU_Status_5.GyroBias_x', 'IQCU_IMU_Status_5.GyroBias_y', 'IQCU_IMU_Status_5.GyroBias_z', 'Radar.Rx_Out_0', 'Radar.Ry_Out_0', 'Radar.Vx_Out_0', 'Radar.Vy_Out_0', 'Radar.Rx_Out_1', 'Radar.Ry_Out_1', 'Radar.Vx_Out_1', 'Radar.Vy_Out_1', 'Radar.Rx_Out_2', 'Radar.Ry_Out_2', 'Radar.Vx_Out_2', 'Radar.Vy_Out_2', 'Radar.Rx_Out_3', 'Radar.Ry_Out_3', 'Radar.Vx_Out_3', 'Radar.Vy_Out_3', 'Radar.Rx_Out_4', 'Radar.Ry_Out_4', 'Radar.Vx_Out_4', 'Radar.Vy_Out_4', 'Radar.Rx_Out_5', 'Radar.Ry_Out_5', 'Radar.Vx_Out_5', 'Radar.Vy_Out_5', 'Radar.Rx_Out_6', 'Radar.Ry_Out_6', 'Radar.Vx_Out_6', 'Radar.Vy_Out_6', 'Radar.Rx_Out_7', 'Radar.Ry_Out_7', 'Radar.Vx_Out_7', 'Radar.Vy_Out_7', 'TTC0001_FMI', 'TTC0001_FOC', 'TTC0002_FMI', 'TTC0002_FOC', 'TTC0003_FMI', 'TTC0003_FOC', 'TTC0004_FMI', 'TTC0004_FOC', 'TTC0005_FMI', 'TTC0005_FOC', 'TTC0006_FMI', 'TTC0006_FOC', 'TTC0007_FMI', 'TTC0007_FOC', 'TTC0008_FMI', 'TTC0008_FOC', 'TTC0009_FMI', 'TTC0009_FOC', 'TTC0010_FMI', 'TTC0010_FOC', 'TTC0011_FMI', 'TTC0011_FOC', 'TTC0012_FMI', 'TTC0012_FOC', 'TTC0013_FMI', 'TTC0013_FOC', 'TTC0014_FMI', 'TTC0014_FOC', 'TTC0015_FMI', 'TTC0015_FOC', 'TTC0016_FMI', 'TTC0016_FOC', 'TTC0017_FMI', 'TTC0017_FOC', 'NavSatNum', 'JammingSt', 'cwSuppress', 'HDOP', 'GpsReset', 'AutoMountState', 'Date']

In [21]:
import sys
sys.path.append(str(ROOT))  # Add the project root to the Python path

from scripts.data_loader import prepare_truck_dataframe, read_nov_data

In [22]:
import scripts.data_loader

print(scripts.data_loader.__file__)

/Users/parisheard/Documents/umich/courses/mastery_project/scripts/data_loader.py

In [23]:
# test the function on one file

path = ROOT / "data" / "nov_data"

lazy1 = read_nov_data(path, "5FT0192")
# Access the specific key in the dictionary returned by read_nov_data
lazy1_data = lazy1.get("5FT0192")  # Replace "5FT0192" with the correct key if needed

# Pass the accessed data to prepare_truck_dataframe
test1 = prepare_truck_dataframe(lazy1_data, "5FT0192")

[loader] 5FT0192: 9 file(s), 294 cols

[loader] Total trucks loaded as LazyFrames: 1
[loader] 5FT0192: collecting LazyFrame ...
[loader] 5FT0192: 4,676,279 rows, 295 cols | 9 time period(s)

In [24]:
# view lazy frame
periods = test1.groupby("time_period")
periods.head()

,Timestamp,EEC1_Engine.ActualEngPercentTorque,EEC1_Engine.DriversDemandEngPercentTorque,EEC1_Engine.EngSpeed,EEC1_Engine.SrcAddrssOfCntrllngDvcForEngCtrl,LFE_Engine.EngFuelRate,EC1_Engine.EngReferenceTorque,EEC2_Engine.AccelPedalPos1,EEC2_Engine.ActlMaxAvailableEngPercentTorque,CCVS1_Engine.BrakeSwitch,...,TTC0017_FMI,TTC0017_FOC,NavSatNum,JammingSt,cwSuppress,HDOP,GpsReset,AutoMountState,Date,time_period
0,2025-11-07 00:00:04.188,27.0,0.0,645.50,0.0,8.50,2402.0,0.0,49.2,0.0,...,255.0,0.0,8.0,0.0,49.0,99.99,0.0,0.0,2025-11-07,1
1,2025-11-07 00:00:04.194,12.0,0.0,648.75,0.0,4.00,2402.0,0.0,40.4,0.0,...,255.0,0.0,1.0,0.0,30.0,99.99,0.0,0.0,2025-11-07,1
2,2025-11-07 00:00:04.196,13.0,0.0,652.25,0.0,4.15,2402.0,0.0,55.6,0.0,...,255.0,0.0,0.0,0.0,0.0,99.99,0.0,0.0,2025-11-07,1
3,2025-11-07 00:00:04.288,26.0,0.0,645.75,0.0,8.60,2402.0,0.0,49.6,0.0,...,255.0,0.0,8.0,0.0,49.0,99.99,0.0,0.0,2025-11-07,1
4,2025-11-07 00:00:04.294,12.0,0.0,649.50,0.0,4.05,2402.0,0.0,40.4,0.0,...,255.0,0.0,1.0,0.0,30.0,99.99,0.0,0.0,2025-11-07,1
8664,2025-11-07 00:00:04.187,0.0,0.0,0.00,0.0,0.00,2402.0,0.0,0.0,0.0,...,255.0,0.0,14.0,0.0,0.0,99.99,0.0,0.0,2025-11-17,2
8665,2025-11-07 00:00:04.187,0.0,0.0,0.00,0.0,0.00,2402.0,0.0,0.0,0.0,...,255.0,0.0,12.0,0.0,47.0,99.99,0.0,0.0,2025-11-17,2
8666,2025-11-07 00:00:04.189,28.0,20.0,627.50,3.0,9.10,2402.0,9.6,42.0,0.0,...,255.0,0.0,10.0,0.0,28.0,99.99,0.0,0.0,2025-11-17,2
8667,2025-11-07 00:00:04.190,54.0,0.0,135.00,0.0,0.00,2402.0,0.0,54.4,0.0,...,255.0,0.0,16.0,0.0,0.0,99.99,0.0,0.0,2025-11-17,2
8668,2025-11-07 00:00:04.196,8.0,0.0,650.75,0.0,2.70,2402.0,0.0,40.4,0.0,...,255.0,0.0,0.0,0.0,0.0,99.99,0.0,0.0,2025-11-17,2
171262,2025-11-07 00:00:04.186,7.0,0.0,650.25,0.0,2.30,2402.0,0.0,40.4,0.0,...,255.0,0.0,11.0,0.0,32.0,99.99,0.0,0.0,2025-11-18,3
171263,2025-11-07 00:00:04.195,8.0,0.0,649.75,0.0,2.55,2402.0,0.0,40.4,0.0,...,255.0,0.0,6.0,0.0,25.0,99.99,0.0,0.0,2025-11-18,3
171264,2025-11-07 00:00:04.286,7.0,0.0,651.25,0.0,2.45,2402.0,0.0,40.4,0.0,...,255.0,0.0,11.0,0.0,32.0,99.99,0.0,0.0,2025-11-18,3
171265,2025-11-07 00:00:04.295,7.0,0.0,653.00,0.0,2.60,2402.0,0.0,40.4,0.0,...,255.0,0.0,7.0,0.0,25.0,99.99,0.0,0.0,2025-11-18,3
171266,2025-11-07 00:00:04.386,7.0,0.0,651.00,0.0,2.25,2402.0,0.0,40.4,0.0,...,255.0,0.0,11.0,0.0,32.0,99.99,0.0,0.0,2025-11-18,3
616775,2025-11-07 00:00:04.183,7.0,0.0,649.00,0.0,2.25,2402.0,0.0,40.4,0.0,...,255.0,0.0,9.0,0.0,23.0,99.99,0.0,0.0,2025-11-19,4
616776,2025-11-07 00:00:04.186,14.0,0.0,648.75,0.0,4.20,0.0,0.0,53.2,0.0,...,255.0,0.0,9.0,0.0,46.0,99.99,0.0,0.0,2025-11-19,4
616777,2025-11-07 00:00:04.193,0.0,0.0,0.00,0.0,0.00,2402.0,0.0,0.0,0.0,...,255.0,0.0,11.0,0.0,27.0,99.99,0.0,0.0,2025-11-19,4
616778,2025-11-07 00:00:04.195,0.0,0.0,0.00,0.0,0.00,2402.0,0.0,0.0,0.0,...,255.0,0.0,15.0,0.0,0.0,99.99,0.0,0.0,2025-11-19,4
616779,2025-11-07 00:00:04.199,0.0,0.0,0.00,0.0,0.00,2402.0,0.0,0.0,0.0,...,255.0,0.0,15.0,0.0,0.0,99.99,0.0,0.0,2025-11-19,4
1075478,2025-11-07 00:00:04.195,11.0,0.0,647.25,0.0,3.10,2402.0,0.0,58.4,0.0,...,255.0,0.0,11.0,0.0,63.0,99.99,0.0,0.0,2025-11-20,5
1075479,2025-11-07 00:00:04.200,6.0,0.0,651.25,0.0,2.05,2402.0,0.0,40.4,0.0,...,255.0,0.0,0.0,0.0,0.0,99.99,0.0,0.0,2025-11-20,5
1075480,2025-11-07 00:00:04.295,12.0,0.0,651.75,0.0,3.45,2402.0,0.0,56.8,0.0,...,255.0,0.0,11.0,0.0,63.0,99.99,0.0,0.0,2025-11-20,5
1075481,2025-11-07 00:00:04.300,6.0,0.0,651.25,0.0,2.00,2402.0,0.0,40.4,0.0,...,255.0,0.0,0.0,0.0,0.0,99.99,0.0,0.0,2025-11-20,5
1075482,2025-11-07 00:00:04.395,10.0,0.0,653.75,0.0,3.00,2402.0,0.0,58.0,0.0,...,255.0,0.0,11.0,0.0,63.0,99.99,0.0,0.0,2025-11-20,5
1576869,2025-11-07 00:00:04.193,11.0,0.0,651.50,0.0,3.25,2402.0,0.0,58.0,0.0,...,255.0,0.0,10.0,0.0,0.0,99.99,0.0,0.0,2025-11-21,6
1576870,2025-11-07 00:00:04.195,6.0,0.0,649.25,0.0,2.00,2402.0,0.0,40.4,0.0,...,255.0,0.0,9.0,0.0,38.0,99.99,0.0,0.0,2025-11-21,6
1576871,2025-11-07 00:00:04.197,6.0,0.0,649.00,0.0,2.15,0.0,0.0,40.4,0.0,...,255.0,0.0,14.0,0.0,41.0,99.99,0.0,0.0,2025-11-21,6
1576872,2025-11-07 00:00:04.293,11.0,0.0,650.50,0.0,3.40,2402.0,0.0,57.6,0.0,...,255.0,0.0,10.0,0.0,0.0,99.99,0.0,0.0,2025-11-21,6
1576873,2025-11-07 00:00:04.295,7.0,0.0,646.50,0.0,2.25,2402.0,0.0,40.4,0.0,...,255.0,0.0,9.0,0.0,38.0,99.99,0.0,0.0,2025-11-21,6
2063344,2025-11-07 00:00:04.187,0.0,0.0,0.00,0.0,0.00,2402.0,0.0,0.0,0.0,...,255.0,0.0,8.0,0.0,32.0,99.99,0.0,0.0,2025-11-22,7
2063345,2025-11-07 00:00:04.191,24.0,0.0,646.75,0.0,7.60,0.0,0.0,51.2,0.0,...,255.0,0.0,10.0,0.0,61.0,99.99,0.0,0.0,2025-11-22,7
2063346,2025-11-07 00:00:04.192,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,...,255.0,0.0,7.0,0.0,62.0,99.99,0.0,0.0,2025-11-22,7
2063347,2025-11-07 00:00:04.194,0.0,0.0,0.00,0.0,0.00,2402.0,0.0,0.0,0.0,...,255.0,0.0,8.0,0.0,0.0,99.99,0.0,0.0,2025-11-22,7
2063348,2025-11-07 00:00:04.194,11.0,0.0,656.75,0.0,3.25,2402.0,0.0,56.4,0.0,...,255.0,0.0,8.0,0.0,35.0,99.99,0.0,0.0,2025-11-22,7
2789896,2025-11-07 00:00:03.374,72.0,95.0,1074.50,0.0,41.85,0.0,87.2,73.2,0.0,...,255.0,0.0,24.0,0.0,0.0,0.84,0.0,0.0,2025-11-25,8
2789897,2025-11-07 00:00:03.474,76.0,95.0,1078.25,0.0,43.40,0.0,87.6,76.4,0.0,...,255.0,0.0,24.0,0.0,0.0,0.88,0.0,0.0,2025-11-25,8
2789898,2025-11-07 00:00:03.574,80.0,96.0,1079.00,0.0,46.10,0.0,88.4,80.4,0.0,...,255.0,0.0,24.0,0.0,0.0,0.88,0.0,0.0,2025-11-25,8
2789899,2025-11-07 00:00:03.674,84.0,101.0,1086.50,0.0,48.40,0.0,95.6,84.8,0.0,...,255.0,0.0,24.0,0.0,16.0,0.87,0.0,0.0,2025-11-25,8
2789900,2025-11-07 00:00:03.774,89.0,103.0,1083.50,0.0,51.30,0.0,99.6,90.0,0.0,...,255.0,0.0,24.0,0.0,16.0,0.87,0.0,0.0,2025-11-25,8
4212342,2025-11-07 03:41:27.779,0.0,0.0,1276.25,17.0,0.00,2402.0,0.0,42.8,0.0,...,255.0,0.0,23.0,0.0,25.0,0.69,0.0,0.0,2025-11-26,9
4212343,2025-11-07 03:41:27.879,0.0,0.0,1274.25,17.0,0.00,2402.0,0.0,42.4,0.0,...,255.0,0.0,23.0,0.0,25.0,0.69,0.0,0.0,2025-11-26,9
4212344,2025-11-07 03:41:27.979,0.0,0.0,1275.50,17.0,0.00,2402.0,0.0,42.4,0.0,...,255.0,0.0,23.0,0.0,25.0,0.69,0.0,0.0,2025-11-26,9
4212345,2025-11-07 03:41:28.079,0.0,0.0,1275.00,17.0,0.00,2402.0,0.0,42.4,0.0,...,255.0,0.0,23.0,0.0,25.0,0.69,0.0,0.0,2025-11-26,9
4212346,2025-11-07 03:41:28.180,0.0,0.0,1273.00,17.0,0.00,2402.0,0.0,42.4,0.0,...,255.0,0.0,23.0,0.0,25.0,0.69,0.0,0.0,2025-11-26,9

In [25]:
# average amount of time of each time period
period_durations = periods['Timestamp'].agg(lambda x: x.max() - x.min())
print(period_durations.describe())

count                            9
mean     0 days 05:54:23.747333333
std      0 days 03:27:37.989345235
min         0 days 00:10:58.522000
25%         0 days 04:33:14.157000
50%         0 days 07:19:44.162000
75%         0 days 07:41:15.116000
max         0 days 10:32:31.458000
Name: Timestamp, dtype: object

In [26]:
# identify a few time period breaks and validate that they are correct
# find the largest time period break

largest_break_idx = period_durations.idxmax()
print(f'Largest time period break: {largest_break_idx} with duration {period_durations[largest_break_idx]} seconds')

# view the truck data around boundaries of the largest break
largest_break_data = test1[test1['time_period'] == largest_break_idx]
view = pd.concat([
	test1[test1['time_period'] == largest_break_idx - 1].tail(),
	test1[test1['time_period'] == largest_break_idx].head()
])
view[['Date', 'Timestamp', 'time_period', 'elapsed_s']]

Largest time period break: 8 with duration 0 days 10:32:31.458000 seconds

KeyError: "['elapsed_s'] not in index"

In [ ]:
# get raw timestamps and find differences
ts_raw = test1['Timestamp']
dts = ts_raw.diff().dt.total_seconds()  # Convert timedelta to seconds

print("Negative Jumps:", (dts < 0).sum())
print("Zero Diffs:", (dts == 0).sum())
print("Positive Diffs:", (dts > 0).sum())
print("Significant Positive Diffs:", (dts > 60).sum())

Negative Jumps: 724
Zero Diffs: 0
Positive Diffs: 4675526
Significant Positive Diffs: 53